-- https://www.roleplay.co.uk/topic/121798-recommend-a-vehicle/
Citizen.CreateThread(function()
	--AddTextEntry("model", "Name")
	--Groups--
	 	---Lost---
		AddTextEntry("hfblrb", "Harley-Davidson Fat Boy Lo Racing Bobber")
		AddTextEntry("hspring", "Harley-Davidson Springer Softail")
		AddTextEntry("hknuckle", "Harley-Davidson Knucklehead")
		AddTextEntry("hvrod", "Harley-Davidson Nightrod")
		AddTextEntry("na25", "Harley Davidson Road King")
		AddTextEntry("g_xlcr", "Harley-Davidson XLCR")
		AddTextEntry("FatBoy", "Harley-Davidson Fatboy")
		---Weazel News---
		AddTextEntry("wnewsheli1", "Weazel News Supervolito")
		AddTextEntry("newsvan", "Weazel News Van")
		AddTextEntry("newsheli2", "Weazel News Supervolito")
		---Richard Majestic---
		AddTextEntry("rmheli", "Richard Majestic Volatus")
	--Gangs--
	AddTextEntry("burrito8", "Burrito Van")
	--Civs--
	AddTextEntry("superb", "Skoda Superb")
	AddTextEntry("skyline", "NISSAN GT-R34")
	AddTextEntry("gtr", "NISSAN GT-R")
	AddTextEntry("oraclestd", "UBERMACH Oracle STD V12")
	AddTextEntry("oracleta", "UBERMACH Oracle A V12")
	AddTextEntry("rm3e36", "BMW E36 M3")
	AddTextEntry("rmodm4", "BMW M4")
	AddTextEntry("m3e36", "BMW E36 1997")
	AddTextEntry("paragonxr", "ENUS Paragon XR")
	AddTextEntry("rcf", "LEXUS RCF")
	AddTextEntry("gt500", "MUSTANG GT500")
	AddTextEntry("ast", "Aston Martin Vanquish")
	AddTextEntry("a45", "Mercedes A45")
	AddTextEntry("spyker", "Spyker C8")
	AddTextEntry("vulcan", "Aston Martin Vulcan")
	AddTextEntry("charger", "Daytona Charger")
	AddTextEntry("firebird", "Pontiac Firebird")
	AddTextEntry("ast", "Aston Martin Vanquish")
	AddTextEntry("dbs", "Aston Martin DBS")
	AddTextEntry("cx75", "Jaguar CX75")
	AddTextEntry("moss", "Mercedes Stirling Moss")
	AddTextEntry("czr1", "Chevrolet Corvette ZR1")
	AddTextEntry("bbentayga", "Bentley Bentayga")
	AddTextEntry("ben17", "Bentley Supersport (2017)")
	AddTextEntry("db7zagato", "Aston Martin DB7")
	AddTextEntry("db905", "Aston Martin DB9")
	AddTextEntry("lx570", "Lexus 570")
	AddTextEntry("tampac", "Tampa Outlaw")
	AddTextEntry("nh2r", "Kawasaki Ninja H2")
	AddTextEntry("lykan", "Lykan Hypersport")
	AddTextEntry("italia458", "Ferrari 458")
	AddTextEntry("bmbobber", "BMW R-75, Bobber")
	AddTextEntry("ttrs", "Audi TT")
	AddTextEntry("contss18", "Bentley Continental")
	AddTextEntry("tuscani", "Hyundai Coupe")
	AddTextEntry("p1", "McLaren P1")
	AddTextEntry("senna", "McLaren Senna")
	AddTextEntry("robin", "Reliant Robin")
	AddTextEntry("yRenault5TA", "Renault 5T")
	AddTextEntry("yRenault5TB", "Renault 5T")
	AddTextEntry("sultanrsv8", "Sultan RSV82")
	AddTextEntry("a45", "Mercedes A45")
	AddTextEntry("v250", "Mercedes Benz V250")
	AddTextEntry("firetruk", "Fire Truck")
	AddTextEntry("rs6", "Audi RS6")
	AddTextEntry("fpace2017", "Jaguar F-Pace")
	AddTextEntry("rs4avant", "Audi RS4 Avant")
	AddTextEntry("e63amg", "Mercedes Benz E63")
	AddTextEntry("ursa", "Porche Macan")
	AddTextEntry("EK9", "Honda Civic")
	AddTextEntry("twizy", "Twizy")
	AddTextEntry("foodcar", "Guidos Take Out")
	AddTextEntry("foodcar2", "Noodle Exchange")
	AddTextEntry("foodcar3", "Grain of Truth")
	AddTextEntry("foodcar4", "Pizza This 1")
	AddTextEntry("foodcar5", "Pizza This 2")
	AddTextEntry("foodcar6", "Pizza Planet")
	AddTextEntry("foodcar7", "China Town Noodle Car")
	AddTextEntry("cbus", "Diamond Casino Bus")
	AddTextEntry("bbus", "Blood Donation Bus")
	AddTextEntry("v850r", "Volvo 850R")
	AddTextEntry("v242", "Volvo 242")
	AddTextEntry("panameragts", "Porsche Panamera GTS")
	AddTextEntry("subwrx", "Subaru Impreza WRX STI")
	AddTextEntry("amggtsprior", "Mercedes-AMG GT S")
	AddTextEntry("e92", "BMW M3 E92")
	AddTextEntry("f82", "F82 M4")
	AddTextEntry("f82st", "F82 M4 ST")
	AddTextEntry("f82duke", "F82 M4 Duke")
	AddTextEntry("f824slw", "F82 M4 SLW")
	AddTextEntry("f82lw", "F82 M4 LW")
	AddTextEntry("f82hs", "F82 M4 HS")
	AddTextEntry("mobilscoot", "Mobility Scooter")
	AddTextEntry("rmodrs7", "Audi RS7 Sportback")
	AddTextEntry("M135i", "BMW M135i")
	AddTextEntry("r820", "Audi R8")
	AddTextEntry("velar", "Range Rover Velar")
	AddTextEntry("cla45sb", "AMG CLA 45")
	AddTextEntry("720s", "McLaren 720s")
	AddTextEntry("a80", "Toyota Supra JZA80")
	AddTextEntry("rx811", "Mazda RX-8 R3")
	AddTextEntry("rs5", "Audi RS5")
	AddTextEntry("giulia", "Alfa Romeo Giulia Guadrifoglio")
	AddTextEntry("w140", "Mercedes-Benz w140 AMG")
	AddTextEntry("mz3", "Volkswagen Speedo 3")
	AddTextEntry("COOPERS", "Austin Mini Cooper S")
	AddTextEntry("ftype", "Jaguar F-Type")
	AddTextEntry("rmodx6", "BMW X6M F16")
	AddTextEntry("993rwb", "Porsche 911 GT2")
	AddTextEntry("e15082", "Ford E-150") 
	AddTextEntry("95y33", "Nissan Cedric")
	AddTextEntry("fury69", "Plymouth Fury III")
	AddTextEntry("MGT", "Ford Mustang GT")
	AddTextEntry("models", "Tesla Model S")
	AddTextEntry("boss302", "Ford Mustang Boss 302")
	AddTextEntry("pistas", "Ferrari 488 Pista Spider")
	AddTextEntry("regera", "Koenigsegg Regera")
	AddTextEntry("mlmansory", "Maserati Levante Mansory")
	AddTextEntry("f625", "Maserati GT")
	AddTextEntry("cali57", "Ferrari 250 GT California Spyder")
	AddTextEntry("fd", "Mazda RX7")
	AddTextEntry("nsr34", "Nissan Skyline R34")
	AddTextEntry("dk350z", "Veilside Nissan 350z")
	AddTextEntry("nsr32", "Nissan Skyline R32")
	AddTextEntry("rx7rb", "Mazda RX7")
	AddTextEntry("s15rb", "Nissan Silvia S15")
	AddTextEntry("rs6c8", "Audi RS6 Sedan")
	AddTextEntry("ffocus", "Ford Focus RS")
	AddTextEntry("mustang65", "Ford Mustang 1965")
	AddTextEntry("nissantitan17", "Nissan Titan Warrior 2017")
	AddTextEntry("m2", "BMW M2")

	AddTextEntry("g65amg", "Mercedes-Benz G65 AMG")
	AddTextEntry("xj", "Jaguar XJ")
	AddTextEntry("aq7", "Audi Q7 2016")
	
	
	-- Nissan Skyline Mod Kit Entries
	AddTextEntry(0x004D4C50, "Nissan")
	AddTextEntry(0x01BD8E8A, "Nismo")
	AddTextEntry(0x03B8ABEA, "Front Standard Plate")
	AddTextEntry(0x0901973A, "Remove Front Plate")
	AddTextEntry(0x0A3BC274, "326 Power")
	AddTextEntry(0x0E160DF6, "Liberty Walk")
	AddTextEntry(0x1AB3B1C1, "Garagemak")
	AddTextEntry(0x2C99B768, "Key's Racing")
	AddTextEntry(0x3F8BE905, "BRIDE")
	AddTextEntry(0x4A59C49C, "V-Carbon")
	AddTextEntry(0x6E1B6170, "Remove Rear Plate")
	AddTextEntry(0x7E39B694, "Skyline GT-R V-Spec II (BNR34)")
	AddTextEntry(0x8B35488C, "Drag")
	AddTextEntry(0x80E6F3B6, "Top Secret Type II")
	AddTextEntry(0x94BAACFF, "Big Bore Exhaust")
	AddTextEntry(0x105F1B4B, "Jun")
	AddTextEntry(0x157E4547, "Z-Tune")
	AddTextEntry(0x241E2F97, "Rollcage")
	AddTextEntry(0x425EC05C, "Top Secret")
	AddTextEntry(0x472DC9B9, "Mine's")
	AddTextEntry(0x486BA84E, "Recaro")
	AddTextEntry(0x2848F7EC, "Liberty  Walk  Big")
	AddTextEntry(0x5748BBD5, "Duck")
	AddTextEntry(0x62283AD4, "Carbon Wing Risers")
	AddTextEntry(0x73396A26, "N1")
	AddTextEntry(0x202964CF, "Rear Standard Plate")
	AddTextEntry(0x283562F7, "AR")
	AddTextEntry(0x60755726, "Mantis")
	AddTextEntry(0xA265C28F, "Voltex")
	AddTextEntry(0xBFBF77F2, "Abflug")
	AddTextEntry(0xE90D99E1, "Uras GT")
	AddTextEntry(0xE342A440, "Sunline")
	AddTextEntry(0xE42668A3, "Big Spoil")
	AddTextEntry(0xF42DADDC, "C-West")
end)
