Citizen.CreateThread(function()
	---Police Marked---
	AddTextEntry("fbi2", "Volvo XC90")
	AddTextEntry("rpPolice1", "Volvo V90")
	AddTextEntry("rpPolice2", "Ford Ranger")
	AddTextEntry("rpPolice3", "540i BMW")
	AddTextEntry("rpPolice4", "Audi A4 TFSI 35")
	AddTextEntry("rpPolice5", "BMW 330D Saloon")
	AddTextEntry("rpPolice6", "Vauxhall Insignia")
	AddTextEntry("rpPolice7", "BMW 3 Series")
	AddTextEntry("rpPolice8", "BMW X5 40d XDrive")
	AddTextEntry("rpPolice9", "Mercedes-Benz Sprinter")
	AddTextEntry("rpPolice10", "BMW M5 interceptor")
	AddTextEntry("rpPolice11", "Skoda Superb Estate")
	AddTextEntry("rpPolice12", "Volvo XC90")
	AddTextEntry("rpPolice13", "atv")
	AddTextEntry("rpPolice14", "Scoda Octavia VRS")
	AddTextEntry("rpPolice15", "Ford Focus")
	---Police UC---
	AddTextEntry("rpPoliceUC1", "[Unmarked] BMW X5")
	AddTextEntry("rpPoliceUC2", "Unmarked Baller")
	AddTextEntry("rpPoliceUC3", "[Unmarked] BMW 530XD")
	AddTextEntry("rpPoliceUC4", "[Unmarked] 2017 Ford Mondeo Saloon")
	AddTextEntry("rpPoliceUC5", "[Unmarked] Ford Ranger 6S")
	AddTextEntry("rpPoliceUC6", "[Unmarked] BMW F10")
	AddTextEntry("rpPoliceUC7", "[Unmarked] Range Rover SVR")
	AddTextEntry("rpPoliceUC8", "[Unmarked] Oracle")
	AddTextEntry("rpPoliceUC6", "[Unmarked] Volvo V90")
	AddTextEntry("sheriff2", "[Unmarked] Granger")
	---Police Boats---
	AddTextEntry("rpPoliceB1", "Police RHIB")
	AddTextEntry("rpPoliceB2", "Police Boat")
	---Police Helis---
	AddTextEntry("rpPoliceH1", "NPAS EC145")
	--NHS
	AddTextEntry("ambulance", "Mercedes-Benz Sprinter Ambu")
	AddTextEntry("rpNHS1", "Mercedes-Benz Sprinter Ambu")
	AddTextEntry("rpNHS2", "Fiat Ducato Ambulance")
	AddTextEntry("rpNHS3", "2017 Range Rover SVR")
	AddTextEntry("rpNHS4", "Skoda Karoq")
	AddTextEntry("rpNHS5", "Mercedes-Benz Vito")
	AddTextEntry("rpNHS6", "BMW R 1200RT")
	AddTextEntry("rpNHS7", "Blood Service Bus")
	AddTextEntry("rpNHSH1", "Eurocopter Med Heli")

	AddTextEntry("scorcher", "Push Bike")


	---Gruppe6---
	AddTextEntry("rpG61", "Gruppe6 Explorer")
	AddTextEntry("rpG62", "[Unmarked] 2012 Renault Premium Lorry")
	AddTextEntry("rpG63", "Gruppe6 P-Bus")
	AddTextEntry("rpG64", "Gruppe6 P-Truck")
	AddTextEntry("rpG65", "Gruppe6 P-Van")
	AddTextEntry("rpG66", "Gruppe6 M-Truck")
	AddTextEntry("rpG67", "Gruppe6 M-Van")
	--Civ
	AddTextEntry("rpCiv1", "Land Rover Discovery 5")
	AddTextEntry("rpCiv2", "Huntingchevy")
	AddTextEntry("rpCiv3", "Flatbed")
end)
