Armory = {}

Armory.AssignedLoadouts = { -- items accessable in shop
	["police"] = {
		{item = "breaching_charge", flag = "firearms", level = 2, price = 10000, label = "Breaching Charge", type = "item_standard"},
		{item = "idcard", flag = "taser", level = 0, price = 100, label = "ID Card", type = "item_standard"},
		{item = "cone", flag = "taser", level = 0, price = 100, label = "Collection Of Cones", type = "item_standard"},
		{item = "evidenceBag", flag = "special", level = 1, price = 100, label = "Evidence Bag", type = "item_standard"},
		{item = "evidence", flag = "special", level = 1, price = 100, label = "Evidence Card", type = "item_standard"},
		{item = "cbarrier", flag = "taser", level = 0, price = 100, label = "Concrete Barrier", type = "item_standard"},
		{item = "gazebo", flag = "taser", level = 0, price = 100, label = "Gazebo", type = "item_standard"},
		{item = "bluelight", flag = "taser", level = 0, price = 100, label = "Bluelight", type = "item_standard"},
		{item = "redlight", flag = "taser", level = 0, price = 100, label = "Redlight", type = "item_standard"},
		{item = "medicBag", flag = "taser", level = 0, price = 100, label = "Medic Bag", type = "item_standard"},
		{item = "workLight", flag = "taser", level = 0, price = 100, label = "Scene Light", type = "item_standard"},
		{item = "fingerprintduster", flag = "cid", level = 1, price = 100, label = "Finger Print Duster", type = "item_standard"},
		{item = "forensicswashkit", flag = "special", level = 1, price = 100, label = "Forensics Washkit", type = "item_standard"},
		{item = "stinger", flag = "driving", level = 1, price = 650, label = "Stinger Set", type = "item_standard"},
		{item = "radio", flag = "taser", level = 0, price = 100, label = "Service Radio", type = "item_standard"},
		{item = "phone", flag = "taser", level = 0, price = 250, label = "SmartPhone", type = "item_standard"},
		{item = "binoculars", flag = "taser", level = 0, price = 100, label = "Binoculars", type = "item_standard"},
		{item = "armor", flag = "taser", level = 0, price = 500, label = "Armor", type = "item_standard"},
		{item = "scuba", flag = "boat", level = 1, price = 200, label = "Oxygen Tank", type = "item_standard"},
		{item = "pistol", flag = "firearms", level = 1, price = 250, label = "Pistol Ammo", type = "item_ammo"},
		{item = "smg", flag = "firearms", level = 2, price = 500, label = "SMG Ammo", type = "item_ammo"},
		{item = "assaultRifle", flag = "firearms", level = 3, price = 625, label = "Rifle Ammo", type = "item_ammo"},
		{item = "sniper", flag = "firearms", level = 4, price = 2500, label = "Sniper Ammo", type = "item_ammo"},
		{item = "beanBag", flag = "firearms", level = 2, price = 125, label = "Baton Launcher Ammo", type = "item_ammo"},
		{item = "tearGas", flag = "firearms", level = 2, price = 500, label = "Tear Gas Ammo", type = "item_ammo"},
		{item = "WEAPON_FLASHLIGHT", flag = "taser", level = 0, price = 100, label = "Flashlight", type = "item_weapon"},
		{item = "WEAPON_NIGHTSTICK", flag = "taser", level = 0, price = 150, label = "ASP", type = "item_weapon"},
		{item = "WEAPON_STUNGUN", flag = "taser", level = 1, price = 10000, label = "Taser", type = "item_weapon"},
		{item = "WEAPON_PISTOL", flag = "firearms", level = 1, price = 20000, label = "Pistol", type = "item_weapon"},
		{item = "WEAPON_COMBATPISTOL", flag = "firearms", level = 1, price = 22000, label = "Combat Pistol", type = "item_weapon"},
		{item = "WEAPON_SMG", flag = "firearms", level = 2, price = 45000, label = "SMG", type = "item_weapon"},
		{item = "WEAPON_SPECIALCARBINE", flag = "firearms", level = 3, price = 55000, label = "Special Carbine", type = "item_weapon"},
		{item = "WEAPON_CARBINERIFLE_MK2", flag = "firearms", level = 4, price = 65000, label = "Carbine MKII", type = "item_weapon"},
		{item = "WEAPON_SNIPERRIFLE", flag = "firearms", level = 4, price = 80000, label = "Operations Sniper Rifle", type = "item_weapon"},
		{item = "WEAPON_GRENADELAUNCHER", flag = "firearms", level = 2, price = 15000, label = "Baton Launcher", type = "item_weapon"},
		{item = "WEAPON_BZGAS", flag = "firearms", level = 2, price = 8000, label = "Tear Gas Canister", type = "item_weapon"},
		{item = "eyeWash", flag = "taser", level = 0, price = 400, label = "Eye Wash", type = "item_standard"},
		{item = "bandage", flag = "taser", level = 0, price = 200, label = "Bandage", type = "item_standard"},
	},
	["ambulance"] = {
		{item = "cone", flag = "firstaid", level = 0, price = 0, label = "Collection Of Cones", type = "item_standard"},
		{item = "cbarrier", flag = "firstaid", level = 0, price = 0, label = "Concrete Barrier", type = "item_standard"},
		{item = "gazebo", flag = "firstaid", level = 0, price = 0, label = "Gazebo", type = "item_standard"},
		{item = "bluelight", flag = "firstaid", level = 0, price = 0, label = "Bluelight", type = "item_standard"},
		{item = "redlight", flag = "firstaid", level = 0, price = 0, label = "Redlight", type = "item_standard"},
		{item = "medicBag", flag = "firstaid", level = 0, price = 0, label = "Medic Bag", type = "item_standard"},
		{item = "idcard", flag = "firstaid", level = 0, price = 0, label = "ID Card", type = "item_standard"},
		{item = "binoculars", flag = "firstaid", level = 0, price = 0, label = "Binoculars", type = "item_standard"},
		{item = "radio", flag = "firstaid", level = 0, price = 100, label = "Service Radio", type = "item_standard"},
		{item = "phone", flag = "firstaid", level = 0, price = 500, label = "SmartPhone", type = "item_standard"},
		{item = "armor", flag = "firstaid", level = 0, price = 350, label = "Armor", type = "item_standard"},
		{item = "WEAPON_FLASHLIGHT", flag = "firstaid", level = 0, price = 0, label = "Flashlight", type = "item_weapon"},
		{item = "bandage", flag = "firstaid", level = 0, price = 200, label = "Bandage", type = "item_standard"},
		{item = "paracetamol", flag = "firstaid", level = 0, price = 160, label = "Paracetamol", type = "item_standard"},
		{item = "comp_drug_morphine", flag = "firstaid", level = 0, price = 0, label = "Morphine", type = "item_standard"},
		{item = "scuba", flag = "firstaid", level = 0, price = 80, label = "Oxygen Tank", type = "item_standard"},
		{item = "eyeWash", flag = "firstaid", level = 0, price = 400, label = "Eye Wash", type = "item_standard"},
		{item = "forensicswashkit", flag = "firstaid", level = 0, price = 0, label = "Cleaning Sponge", type = "item_standard"}
	},
	["gruppe6"] = {
		{item = "cone", flag = "gruppe6", level = 1, price = 250, label = "Collection Of Cones", type = "item_standard"},
		{item = "cbarrier", flag = "gruppe6", level = 1, price = 500, label = "Concrete Barrier", type = "item_standard"},
		{item = "gazebo", flag = "gruppe6", level = 1, price = 100, label = "Gazebo", type = "item_standard"},
		{item = "bluelight", flag = "gruppe6", level = 1, price = 100, label = "Bluelight", type = "item_standard"},
		{item = "redlight", flag = "gruppe6", level = 1, price = 100, label = "Redlight", type = "item_standard"},
		{item = "medicBag", flag = "gruppe6", level = 1, price = 100, label = "Medic Bag", type = "item_standard"},
		{item = "idcard", flag = "gruppe6", level = 1, price = 100, label = "ID Card", type = "item_standard"},
		{item = "radio", flag = "gruppe6", level = 1, price = 100, label = "Service Radio", type = "item_standard"},
		{item = "phone", flag = "gruppe6", level = 1, price = 250, label = "SmartPhone", type = "item_standard"},
		{item = "binoculars", flag = "gruppe6", level = 1, price = 100, label = "Binoculars", type = "item_standard"},
		{item = "pistol", flag = "gruppe6", level = 2, price = 250, label = "Pistol Ammo", type = "item_ammo"},
		{item = "beanBag", flag = "gruppe6", level = 2, price = 125, label = "Baton Launcher Ammo", type = "item_ammo"},
		{item = "WEAPON_FLASHLIGHT", flag = "gruppe6", level = 1, price = 100, label = "Flashlight", type = "item_weapon"},
		{item = "WEAPON_NIGHTSTICK", flag = "gruppe6", level = 1, price = 150, label = "ASP", type = "item_weapon"},
		{item = "armor", flag = "gruppe6", level = 1, price = 250, label = "Armor", type = "item_standard"},
		{item = "WEAPON_STUNGUN", flag = "gruppe6", level = 2, price = 5000, label = "Taser", type = "item_weapon"},
		{item = "WEAPON_PISTOL", flag = "gruppe6", level = 2, price = 10000, label = "Pistol", type = "item_weapon"},
		{item = "WEAPON_GRENADELAUNCHER", flag = "gruppe6", level = 2, price = 7500, label = "Baton Launcher", type = "item_weapon"},
		{item = "eyeWash", flag = "gruppe6", level = 0, price = 400, label = "Eye Wash", type = "item_standard"},
		{item = "bandage", flag = "gruppe6", level = 0, price = 200, label = "Bandage", type = "item_standard"},
		{item = "forensicswashkit", flag = "gruppe6", level = 0, price = 100, label = "Cleaning Sponge", type = "item_standard"}
	},
}
