metalDetectors = {}

metalDetectors.Detectors = {
	Court_1 = {
		Location = BoxZone:Create(vector3(-577.36, -201.72, 38.22), 1.0, 1.4, {
			heading=300,
			-- debugPoly=true,
			minZ=35.42,
			maxZ=39.42
		}),
		Online = true,
		Restriction = {"WEAPON_PISTOL", "WEAPON_COMBATPISTOL", "WEAPON_SMG", "WEAPON_VINTAGEPISTOL", "WEAPON_PISTOL50","WEAPON_COMBATPDW", "WEAPON_CARBINERIFLE", "WEAPON_ADVANCEDRIFLE","WEAPON_MICROSMG", "WEAPON_DOUBLEACTION", "WEAPON_MACHINEPISTOL", "WEAPON_COMPACTRIFLE", "weapon_knife", "WEAPON_BAT", "WEAPON_BOTTLE", "WEAPON_CROWBAR", "WEAPON_POOLCUE", "WEAPON_GOLFCLUB", "WEAPON_HAMMER", "WEAPON_HATCHET", "WEAPON_DAGGER", "WEAPON_KNUCKLE", "WEAPON_KNIFE", "WEAPON_MACHETE", "WEAPON_SWITCHBLADE", "WEAPON_WRENCH"},
		Access = {"gruppe6"}
	},
	Court_2 = {
		Location = BoxZone:Create(vector3(-580.15, -203.45, 38.22), 1.0, 1.4, {
			heading=120,
			-- debugPoly=true,
			minZ=35.42,
			maxZ=39.42
		}),
		Online = true,
		Restriction = {"WEAPON_PISTOL", "WEAPON_COMBATPISTOL", "WEAPON_SMG", "WEAPON_VINTAGEPISTOL", "WEAPON_PISTOL50","WEAPON_COMBATPDW", "WEAPON_CARBINERIFLE", "WEAPON_ADVANCEDRIFLE","WEAPON_MICROSMG", "WEAPON_DOUBLEACTION", "WEAPON_MACHINEPISTOL", "WEAPON_COMPACTRIFLE", "weapon_knife", "WEAPON_BAT", "WEAPON_BOTTLE", "WEAPON_CROWBAR", "WEAPON_POOLCUE", "WEAPON_GOLFCLUB", "WEAPON_HAMMER", "WEAPON_HATCHET", "WEAPON_DAGGER", "WEAPON_KNUCKLE", "WEAPON_KNIFE", "WEAPON_MACHETE", "WEAPON_SWITCHBLADE", "WEAPON_WRENCH"},
		Access = {"gruppe6"}
	},
	Court_3 = {
		Location = BoxZone:Create(vector3(-550.34, -196.3, 38.22), 1.0, 1.4, {
			heading=300,
			-- debugPoly=true,
			minZ=35.42,
			maxZ=39.42
		}),
		Online = true,
		Restriction = {"WEAPON_PISTOL", "WEAPON_COMBATPISTOL", "WEAPON_SMG", "WEAPON_VINTAGEPISTOL", "WEAPON_PISTOL50","WEAPON_COMBATPDW", "WEAPON_CARBINERIFLE", "WEAPON_ADVANCEDRIFLE","WEAPON_MICROSMG", "WEAPON_DOUBLEACTION", "WEAPON_MACHINEPISTOL", "WEAPON_COMPACTRIFLE", "weapon_knife", "WEAPON_BAT", "WEAPON_BOTTLE", "WEAPON_CROWBAR", "WEAPON_POOLCUE", "WEAPON_GOLFCLUB", "WEAPON_HAMMER", "WEAPON_HATCHET", "WEAPON_DAGGER", "WEAPON_KNUCKLE", "WEAPON_KNIFE", "WEAPON_MACHETE", "WEAPON_SWITCHBLADE", "WEAPON_WRENCH"},
		Access = {"gruppe6"}
	},
	Court_4 = {
		Location = BoxZone:Create(vector3(-549.23, -195.63, 38.22), 1.0, 1.4, {
			heading=300,
			-- debugPoly=true,
			minZ=35.42,
			maxZ=39.42
		}),
		Online = true,
		Restriction = {"WEAPON_PISTOL", "WEAPON_COMBATPISTOL", "WEAPON_SMG", "WEAPON_VINTAGEPISTOL", "WEAPON_PISTOL50","WEAPON_COMBATPDW", "WEAPON_CARBINERIFLE", "WEAPON_ADVANCEDRIFLE","WEAPON_MICROSMG", "WEAPON_DOUBLEACTION", "WEAPON_MACHINEPISTOL", "WEAPON_COMPACTRIFLE", "weapon_knife", "WEAPON_BAT", "WEAPON_BOTTLE", "WEAPON_CROWBAR", "WEAPON_POOLCUE", "WEAPON_GOLFCLUB", "WEAPON_HAMMER", "WEAPON_HATCHET", "WEAPON_DAGGER", "WEAPON_KNUCKLE", "WEAPON_KNIFE", "WEAPON_MACHETE", "WEAPON_SWITCHBLADE", "WEAPON_WRENCH"},
		Access = {"gruppe6"}
	},
	Court_5 = {
		Location = BoxZone:Create(vector3(-530.77, -176.1, 38.22), 1.0, 1.4, {
			heading=300,
			-- debugPoly=true,
			minZ=35.42,
			maxZ=39.42
		}),
		Online = true,
		Restriction = {"WEAPON_PISTOL", "WEAPON_COMBATPISTOL", "WEAPON_SMG", "WEAPON_VINTAGEPISTOL", "WEAPON_PISTOL50","WEAPON_COMBATPDW", "WEAPON_CARBINERIFLE", "WEAPON_ADVANCEDRIFLE","WEAPON_MICROSMG", "WEAPON_DOUBLEACTION", "WEAPON_MACHINEPISTOL", "WEAPON_COMPACTRIFLE", "weapon_knife", "WEAPON_BAT", "WEAPON_BOTTLE", "WEAPON_CROWBAR", "WEAPON_POOLCUE", "WEAPON_GOLFCLUB", "WEAPON_HAMMER", "WEAPON_HATCHET", "WEAPON_DAGGER", "WEAPON_KNUCKLE", "WEAPON_KNIFE", "WEAPON_MACHETE", "WEAPON_SWITCHBLADE", "WEAPON_WRENCH"},
		Access = {"gruppe6"}
	},
	Court_6 = {
		Location = BoxZone:Create(vector3(-527.43, -174.11, 38.22), 1, 1.4, {
			heading=300,
			-- debugPoly=true,
			minZ=35.42,
			maxZ=39.42
		}),
		Online = true,
		Restriction = {"WEAPON_PISTOL", "WEAPON_COMBATPISTOL", "WEAPON_SMG", "WEAPON_VINTAGEPISTOL", "WEAPON_PISTOL50","WEAPON_COMBATPDW", "WEAPON_CARBINERIFLE", "WEAPON_ADVANCEDRIFLE","WEAPON_MICROSMG", "WEAPON_DOUBLEACTION", "WEAPON_MACHINEPISTOL", "WEAPON_COMPACTRIFLE", "weapon_knife", "WEAPON_BAT", "WEAPON_BOTTLE", "WEAPON_CROWBAR", "WEAPON_POOLCUE", "WEAPON_GOLFCLUB", "WEAPON_HAMMER", "WEAPON_HATCHET", "WEAPON_DAGGER", "WEAPON_KNUCKLE", "WEAPON_KNIFE", "WEAPON_MACHETE", "WEAPON_SWITCHBLADE", "WEAPON_WRENCH"},
		Access = {"gruppe6"}
	},
	Court_7 = {
		Location = BoxZone:Create(vector3(-511.83, -209.93, 38.22), 1, 1.4, {
			heading=30,
			--debugPoly=true,
			minZ=35.42,
			maxZ=39.42
		}),
		Online = true,
		Restriction = {"WEAPON_PISTOL", "WEAPON_COMBATPISTOL", "WEAPON_SMG", "WEAPON_VINTAGEPISTOL", "WEAPON_PISTOL50","WEAPON_COMBATPDW", "WEAPON_CARBINERIFLE", "WEAPON_ADVANCEDRIFLE","WEAPON_MICROSMG", "WEAPON_DOUBLEACTION", "WEAPON_MACHINEPISTOL", "WEAPON_COMPACTRIFLE", "weapon_knife", "WEAPON_BAT", "WEAPON_BOTTLE", "WEAPON_CROWBAR", "WEAPON_POOLCUE", "WEAPON_GOLFCLUB", "WEAPON_HAMMER", "WEAPON_HATCHET", "WEAPON_DAGGER", "WEAPON_KNUCKLE", "WEAPON_KNIFE", "WEAPON_MACHETE", "WEAPON_SWITCHBLADE", "WEAPON_WRENCH"},
		Access = {"gruppe6"}
	},
	Court_8 = {
		Location = BoxZone:Create(vector3(-512.62, -208.95, 38.22), 1.0, 1.4, {
			heading=30,
			--debugPoly=true,
			minZ=35.42,
			maxZ=39.42
		}),
		Online = true,
		Restriction = {"WEAPON_PISTOL", "WEAPON_COMBATPISTOL", "WEAPON_SMG", "WEAPON_VINTAGEPISTOL", "WEAPON_PISTOL50","WEAPON_COMBATPDW", "WEAPON_CARBINERIFLE", "WEAPON_ADVANCEDRIFLE","WEAPON_MICROSMG", "WEAPON_DOUBLEACTION", "WEAPON_MACHINEPISTOL", "WEAPON_COMPACTRIFLE", "weapon_knife", "WEAPON_BAT", "WEAPON_BOTTLE", "WEAPON_CROWBAR", "WEAPON_POOLCUE", "WEAPON_GOLFCLUB", "WEAPON_HAMMER", "WEAPON_HATCHET", "WEAPON_DAGGER", "WEAPON_KNUCKLE", "WEAPON_KNIFE", "WEAPON_MACHETE", "WEAPON_SWITCHBLADE", "WEAPON_WRENCH"},
		Access = {"gruppe6"}
	},
	Prison_1 = {
		Location = BoxZone:Create(vector3(1843.22, 2585.86, 46.01), 1, 1.4, {
			heading=90,
			--debugPoly=true,
			minZ=43.41,
			maxZ=47.41
		}),
		Online = true,
		Restriction = {"WEAPON_PISTOL", "WEAPON_COMBATPISTOL", "WEAPON_SMG", "WEAPON_VINTAGEPISTOL", "WEAPON_PISTOL50","WEAPON_COMBATPDW", "WEAPON_CARBINERIFLE", "WEAPON_ADVANCEDRIFLE","WEAPON_MICROSMG", "WEAPON_DOUBLEACTION", "WEAPON_MACHINEPISTOL", "WEAPON_COMPACTRIFLE", "weapon_knife", "WEAPON_BAT", "WEAPON_BOTTLE", "WEAPON_CROWBAR", "WEAPON_POOLCUE", "WEAPON_GOLFCLUB", "WEAPON_HAMMER", "WEAPON_HATCHET", "WEAPON_DAGGER", "WEAPON_KNUCKLE", "WEAPON_KNIFE", "WEAPON_MACHETE", "WEAPON_SWITCHBLADE", "WEAPON_WRENCH"},
		Access = {"gruppe6", "police"}
	},
	Prison_2 = {
		Location = BoxZone:Create(vector3(1834.0, 2594.39, 46.01), 1, 1.4, {
			heading=90,
			--debugPoly=true,
			minZ=43.41,
			maxZ=47.41
		}),
		Online = true,
		Restriction = {"WEAPON_PISTOL", "WEAPON_COMBATPISTOL", "WEAPON_SMG", "WEAPON_VINTAGEPISTOL", "WEAPON_PISTOL50","WEAPON_COMBATPDW", "WEAPON_CARBINERIFLE", "WEAPON_ADVANCEDRIFLE","WEAPON_MICROSMG", "WEAPON_DOUBLEACTION", "WEAPON_MACHINEPISTOL", "WEAPON_COMPACTRIFLE", "weapon_knife", "WEAPON_BAT", "WEAPON_BOTTLE", "WEAPON_CROWBAR", "WEAPON_POOLCUE", "WEAPON_GOLFCLUB", "WEAPON_HAMMER", "WEAPON_HATCHET", "WEAPON_DAGGER", "WEAPON_KNUCKLE", "WEAPON_KNIFE", "WEAPON_MACHETE", "WEAPON_SWITCHBLADE", "WEAPON_WRENCH"},
		Access = {"gruppe6", "police"}
	},
	Fight_Club_1 = {
		Location = BoxZone:Create(vector3(927.32, -1802.87, 24.97), 1, 1.4, {
			heading=85,
			--debugPoly=true,
			minZ=22.17,
			maxZ=26.17
		}),
		Online = true,
		Restriction = {"WEAPON_PISTOL", "WEAPON_COMBATPISTOL", "WEAPON_SMG", "WEAPON_VINTAGEPISTOL", "WEAPON_PISTOL50","WEAPON_COMBATPDW", "WEAPON_CARBINERIFLE", "WEAPON_ADVANCEDRIFLE","WEAPON_MICROSMG", "WEAPON_DOUBLEACTION", "WEAPON_MACHINEPISTOL", "WEAPON_COMPACTRIFLE", "weapon_knife", "WEAPON_BAT", "WEAPON_BOTTLE", "WEAPON_CROWBAR", "WEAPON_POOLCUE", "WEAPON_GOLFCLUB", "WEAPON_HAMMER", "WEAPON_HATCHET", "WEAPON_DAGGER", "WEAPON_KNUCKLE", "WEAPON_KNIFE", "WEAPON_MACHETE", "WEAPON_SWITCHBLADE", "WEAPON_WRENCH"},
		Access = {"lost"}
	},
}
